workflows:
  - name: cd
    # This will be resolved in:
    #   https://github.com/exasol/exasol-python-test-framework/issues/102
    remove_jobs:
      - publish-docs
  - name: checks
    remove_jobs:
      # This will be resolved in:
      #   https://github.com/exasol/exasol-python-test-framework/issues/102
      - build-documentation-and-check-links
      # This will be resolved in:
      #   https://github.com/exasol/exasol-python-test-framework/issues/104
      - check-format
      # This will be resolved in:
      #   https://github.com/exasol/exasol-python-test-framework/issues/103
      - lint-typing
      # This job will be re-activated in:
      #   https://github.com/exasol/exasol-python-test-framework/issues/105
      - check-workflows