[tool.poetry]
name = "exasol-python-test-framework"
version = "0.3.0"
description = "Python Test framework for Exasol database tests"

license = "MIT"

authors = [
    "Exasol AG <opensource@exasol.com>"
]

readme = 'README.md'  # Markdown files are supported

repository = "https://github.com/exasol/exasol-python-test-framework"
homepage = "https://github.com/exasol/exasol-python-test-framework"

include = ["exatest","udf"]
keywords = ['exasol', 'testing']

exclude = ["lang"]


[tool.poetry.dependencies]
python = ">=3.6,<4"
pyodbc = ">=4.0.27"
numpy = ">=1.19.5"
scipy = ">=1.2.1"
docker = ">=5.0.3"
pyftpdlib = ">=1.5.6"

[tool.poetry.dev-dependencies]
toml = ">=0.10.2"
gitpython = ">=2.1.0"