[tool.poetry]
name = "exasol-python-test-framework"
version = "0.5.0"
description = "Python Test framework for Exasol database tests"

license = "MIT"

authors = [
    "Exasol AG <opensource@exasol.com>"
]

readme = 'README.md'  # Markdown files are supported

repository = "https://github.com/exasol/exasol-python-test-framework"
homepage = "https://github.com/exasol/exasol-python-test-framework"

include = ["exatest","udf"]
keywords = ['exasol', 'testing']

exclude = ["lang"]


[tool.poetry.dependencies]
python = ">=3.8,<3.11"
pyodbc = "^4.0.27"
numpy = ">=1.22"
scipy = "^1.7.0"
# The `sys_platform` marker makes sure the docker dependency is only installed on
# non windows platforms.
docker = { version = ">=5.0.3", markers = "sys_platform != 'win32'"}
pyftpdlib = ">=1.5.6"

[tool.poetry.dev-dependencies]
toml = ">=0.10.2"
gitpython = ">=3.1.0"
[tool.poetry.group.dev.dependencies]
exasol-integration-test-docker-environment = {url = "https://github.com/exasol/integration-test-docker-environment/releases/download/1.1.0/exasol_integration_test_docker_environment-1.1.0-py3-none-any.whl"}

