name: CI

on: [push, pull_request]

jobs:
  integration_tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Get ODBC driver
        run: |
          bash .github/workflows/scripts/download_odbc_driver.sh "$(pwd)/.."
      - name: Get EXAPLUS
        run: |
          bash .github/workflows/scripts/download_exaplus.sh "$(pwd)/.."
      - name: Setup Python 3.8 for integration-test-docker-environment
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Poetry
        uses: abatilo/actions-poetry@v2.1.6
        with:
          poetry-version: 1.2.1
      - name: Install dependencies
        run: poetry install
      - name: Spawn EXASOL environemnt
        run: poetry run python3 -m exasol_integration_test_docker_environment.main spawn-test-environment --environment-name test --database-port-forward 8888 --bucketfs-forward 6666
      - name: Run all tests
        run: ./scripts/test/run_all_tests.sh "localhost:8888" ../downloads/ODBC/lib/linux/x86_64/libexaodbc-uo2214lv2.so
        env:
          EXAPLUS: ../downloads/EXAPLUS
          TEST_DOCKER_NETWORK_NAME: db_network_test
          TEST_ENVIRONMENT_NAME: test

