name: CI

on:
  push:

jobs:
  integration_tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.10', '3.11', '3.12']
    steps:
      - uses: actions/checkout@v4
      - name: Get ODBC driver
        run: |
          bash .github/workflows/scripts/download_odbc_driver.sh "$(pwd)/.."
      - name: Get EXAPLUS
        run: |
          bash .github/workflows/scripts/download_exaplus.sh "$(pwd)/.."
      - name: Setup Python & Poetry Environment
        uses: ./.github/actions/prepare_poetry_env
        with:
          python-version: ${{ matrix.python-version }}
      - name: Spawn EXASOL environemnt
        run: |
          poetry run python3 -m exasol_integration_test_docker_environment.main spawn-test-environment --environment-name test --database-port-forward 8888 --bucketfs-port-forward 6666
          sleep 120 # wait for SLC to be unpacked
      - name: Show docker networks
        run: |
          docker network ls
      - name: Run all tests
        run: ./scripts/test/run_all_tests.sh "localhost:8888" ../downloads/ODBC/lib/linux/x86_64/libexaodbc-uo2214lv2.so
        env:
          EXAPLUS: ../downloads/EXAPLUS
          TEST_DOCKER_NETWORK_NAME: db_network_test
          TEST_ENVIRONMENT_NAME: test

