name: Release Droid - Upload GitHub Release Assets

on:
  workflow_dispatch:
    inputs:
      upload_url:
        description: 'Upload URL'
        required: true


jobs:
  check-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Python 3.8 for exasol-python-test-framework
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Poetry
        uses: abatilo/actions-poetry@v2.1.6
        with:
          poetry-version: 1.2.1

      - name: Check Release
        run: ./scripts/build/check_release.sh

  integration-tests:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      - name: Get ODBC driver
        run: |
          bash .github/workflows/scripts/download_odbc_driver.sh "$(pwd)/.."
      - name: Get EXAPLUS
        run: |
          bash .github/workflows/scripts/download_exaplus.sh "$(pwd)/.."
      - name: Setup Python 3.8 for integration-test-docker-environment
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Poetry
        uses: abatilo/actions-poetry@v2.1.6
        with:
          poetry-version: 1.2.1
      - name: Install dependencies
        run: poetry install
      - name: Spawn EXASOL environemnt
        run: poetry run python3 -m exasol_integration_test_docker_environment.main spawn-test-environment --environment-name test --database-port-forward 8888 --bucketfs-forward 6666
      - name: Run all tests
        run: ./scripts/test/run_all_tests.sh "localhost:8888" ../downloads/ODBC/lib/linux/x86_64/libexaodbc-uo2214lv2.so
        env:
          EXAPLUS: ../downloads/EXAPLUS
          TEST_DOCKER_NETWORK_NAME: db_network_test
          TEST_ENVIRONMENT_NAME: test

  upload:
    runs-on: ubuntu-18.04
    needs: [integration-tests, check-release]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python 3.8 for release
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Poetry
        uses: abatilo/actions-poetry@v2.1.6
        with:
          poetry-version: 1.2.1
      - name: Build Release
        run: |
          bash ./scripts/build/build_release.sh
      - name: Upload assets to the GitHub release draft
        uses: shogo82148/actions-upload-release-asset@v1
        with:
          upload_url: ${{ github.event.inputs.upload_url }}
          asset_path: dist/*

