name: Slow-Checks

on:
  workflow_call:

jobs:
  run-integration-tests:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.10', '3.11', '3.12']
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - name: Get ODBC driver
        id: get-odbc-driver
        run: |
          FILE=$(bash .github/workflows/scripts/download_odbc_driver.sh "$(pwd)/..")
          echo so-file="$FILE" >> "$GITHUB_OUTPUT"
      - name: Check ODBC File
        run: |
          if [ ! -f "${STEPS_GET_ODBC_DRIVER_OUTPUTS_SO_FILE}" ]
          then
              echo "ODBC file not found"
              exit 1
          else
              echo "ODBC File found."
          fi
        env:
          STEPS_GET_ODBC_DRIVER_OUTPUTS_SO_FILE: ${{ steps.get-odbc-driver.outputs.so-file }}
      - name: Get EXAPLUS
        run: bash .github/workflows/scripts/download_exaplus.sh "$(pwd)/.."
      - name: Setup Python & Poetry Environment
        uses: exasol/python-toolbox/.github/actions/python-environment@v8
        with:
          python-version: ${{ matrix.python-version }}
          poetry-version: "2.3.0"
      - name: Spawn EXASOL environment
        run: |
          poetry run -- python3 -m exasol_integration_test_docker_environment.main \
              spawn-test-environment \
              --environment-name test \
              --database-port-forward 8888 \
              --bucketfs-port-forward 6666
          sleep 120 # wait for SLC to be unpacked
      - name: Run all tests
        run: |
          poetry run -- scripts/test/run_locally.sh \
             --server "localhost:8888" \
             --odbc-driver="${STEPS_GET_ODBC_DRIVER_OUTPUTS_SO_FILE}"
        env:
          EXAPLUS: ../downloads/EXAPLUS
          TEST_DOCKER_NETWORK_NAME: db_network_test
          TEST_ENVIRONMENT_NAME: test
          STEPS_GET_ODBC_DRIVER_OUTPUTS_SO_FILE: ${{ steps.get-odbc-driver.outputs.so-file }}
