name: 'Prepare Poetry environment'
description: 'This composite actions checks out out the project, installs Poetry, and install the project in the Poetry environment'
inputs:
  python-version:
    description: 'The Python version to use'
    required: true
    default: '3.10'
runs:
  using: "composite"
  steps:
    - name: Install poetry
      run: pipx install poetry==1.8.2
      shell: bash
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
        cache: 'poetry'
    - name: Poetry install
      run: poetry install
      shell: bash
